---
# tasks file for roles/grafana
- name: Install GPG and software-properties-common   # GPG와 software-properties-common 설치
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Add Grafana GPG Key   # Grafana의 GPG 키를 시스템에 추가
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no

- name: Add Grafana Repository  # Grafana의 리포지토리를 시스템에 추가
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: no

- name: Install Grafana  # Grafana를 설치
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Start Grafana Service  # Grafana 서비스를 시작
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Wait for Grafana Service Startup  # Grafana 서비스가 정상적으로 시작되었는지 확인
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: Reset Grafana Admin Password  # Grafana의 관리자 비밀번호를 재설정
  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0
