---
- hosts: all
  become: yes
  roles:
  - grafana
  - prometheus.prometheus.node_exporter
  - prometheus.prometheus.prometheus
  - prometheus.prometheus.alertmanager
  
  vars:
    grafana_admin_password: "admin"
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - node.demo.do.prometheus.io
        labels:
          env: demosite
    alertmanager_version: latest
    alertmanager_slack_api_url: "http://example.com"
    alertmanager_receivers:
      - name: slack
        slack_configs:
          - send_resolved: true
            channel: '#alerts'
    alertmanager_route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: slack